# Generated by Django 2.2.3 on 2019-10-07 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airlines',
            name='delete_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='delete_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 17, 38, 56, 240837)),
        ),
    ]
