# Generated by Django 2.2.3 on 2019-10-08 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191007_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delete_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 12, 52, 12, 288663)),
        ),
    ]
