# Generated by Django 2.2.3 on 2019-10-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191008_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delete_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 8, 15, 22, 42, 240086)),
        ),
    ]
