# Generated by Django 2.2.3 on 2019-10-09 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191008_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delete_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 11, 14, 32, 248724)),
        ),
    ]
